name: Build and publish docker image

on:
  push:
    branches:
      - master
    paths:
      - VERSION

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get docker image version
      id: get_version
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        provenance: false
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/nve-hydapi-exporter:${{ steps.get_version.outputs.version }},ghcr.io/${{ github.repository_owner }}/nve-hydapi-exporter:latest
